# A demo CRD for the Kopf example operators.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustersecrets.clustersecret.io
spec:
  scope: Namespaced
  group: clustersecret.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: ClusterSecret
    plural: clustersecrets
    singular: clustersecret
    shortNames:
      - csec
  # additionalPrinterColumns:
  #   - name: ID
  #     type: integer
  #     priority: 0
  #     JSONPath: .status.create_fn.id
  #     description: Ticket ID
  #   - name: Subject
  #     type: string
  #     priority: 0
  #     JSONPath: .subject
  #   - name: Status
  #     type: string
  #     priority: 0
  #     JSONPath: .ticket_status
