apiVersion: cert-manager.io/v1alpha2
kind: Issuer #ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: bl.shlomi@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        clouddns:
          # The ID of the GCP project
          project: "develeap" #$PROJECT_ID
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
            


      #        solvers:
      # - dns01:
      #   providers:
      #   - name: clouddns
      #     clouddns:
      #       # The ID of the GCP project
      #       project: "develeap" #$PROJECT_ID
      #       # This is the secret used to access the service account
      #       serviceAccountSecretRef:
      #         name: clouddns-dns01-solver-svc-acct
      #         key: key.json